name: mobile
description: "Coffee Beans World - Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Routing
  go_router: ^14.6.2
  
  # Networking
  dio: ^5.7.0
  
  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Images
  cached_network_image: ^3.4.1
  
  # UI Components
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  badges: ^3.1.2
  
  # Forms & Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0
  
  # Utils
  intl: any
  equatable: ^2.0.5
  collection: ^1.18.0
  video_player: ^2.10.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  
  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  app_links: ^6.4.1
  google_sign_in: ^7.2.0
  countries_world_map: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/

  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
